name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir ".ssh"
      - run: echo "$" > ".ssh/authorized_keys"
      - run: chmod 600 ".ssh/authorized_keys"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: cd app && rsync -e "ssh -p 20022 -i .ssh/authorized_keys -o StrictHostKeyChecking=no" --archive --compress --delete . root@mebeleiya.space:/home/mebeleiya/www